name: Playwright Tests
on:
  push:
    branches: [main, master]
#   pull_request:
#     branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        run: npm test
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: test-results/reports/
          retention-days: 30
          
      - name: Deploy Playwright report to GitHub Pages
        if: ${{ !cancelled() }} # Optional: to only run if the job wasn't cancelled
        run: |
          git config --global user.name 'Adeyeye Olushola'
          git config --global user.email 'adeyeyeolushola977@gmail.com'

          git status
          git add -A
          git commit -m "add test result"

          git checkout --orphan report-branch # Create a new branch without history
          git clean -fdx # remove gitignored files and folders
          git rm -rf . # remove all git tracked files and folders
          git checkout main -- test-results/reports

          mv test-results/reports/* . # Move the contents to the root

          git add test-results

          git commit -m 'Deploy test-results to new branch'
          git push origin report-branch --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
